name: Sales_Team_App_Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn    
      - name: Run unit tests
        run: yarn test:unit
      - name: Generate build
        run: yarn build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: sales-team-app-performance
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: sales-team-app-performance
      # Deploy to S3 Bucket
      - name: Deploy to S3
        uses: shinyinc/action-aws-cli@v1.2
        run: aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET_NAME }}/dist
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}